[package]
name = "profiles_alt_coordinator"
version = "0.2.0"
rust-version = "1.75.0"
edition = "2021"
authors = ["ddd-mtl"]
description = "Alternate coordinator zome for Profiles"
repository = "https://github.com/ddd-mtl/profiles_alt_zome"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
hdk.workspace = true
zome_utils.workspace = true
zome_signals.workspace = true

hc_zome_profiles_integrity = {path = "../integrity"}


