[package]
name = "shared_ownership_integrity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#derive_more = "0"
#getrandom = { version = "=0.2.12", features = ["js"] }
serde.workspace = true
holochain_serialized_bytes.workspace = true
hdi.workspace = true
